services:
    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments:
            - "@mailer"
            - %locale%
            - 50

    # Fixtures services
    OC\PlatformBundle\DataFixtures\ORM\LoadCategory:
        tags: [doctrine.fixture.orm]