<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdverts($page, $nbPerPage)
    {
        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.image', 'i')
            ->addSelect('i')
            ->leftJoin('a.categories', 'c')
            ->addSelect('c')
            ->orderBy('a.date', 'DESC')
            ->getQuery()
        ;

        $query
            ->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage)
        ;

        return new Paginator($query, true);
    }


    public function getAdvertWithCategories(array $categoryNames)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->leftJoin('a.categories', 'c')
            ->addSelect('c');

        $qb->where($qb->expr()->in('c.name', $categoryNames));

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function getAdvertsWithoutApplication($days) {
        $date = new \DateTime('now');
        $date->sub(new \DateInterval('P'.$days.'D'));
    
        $qb = $this->createQueryBuilder('a')
            ->where('a.applications IS EMPTY')
            ->andWhere('a.date < :date')
            ->andWhere('a.updatedAt IS NULL OR a.updatedAt < :date')
        ;
    
        $qb->setParameters(
            array('date' => $date)
        );
    
        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
